server {
    listen       80;
    listen  [::]:80;
    server_name _;

    access_log /var/log/nginx/host.access.log  main;

    gzip on;
    gzip_comp_level 6;
    gzip_types
        text/html
        text/css
        application/javascript
        image/svg+xml
        font/woff2;

    root /usr/share/nginx/html;

    location / {
        index index.html;
    }
}